# Points别名
name: '点券'

# 是否启用插件
enable: true

# 是否启用 PlaceholderAPI 变量
enable_papi: true

# 是否启用连续执行
# 启用时，当一次性满足多个奖励组的条件时，依次执行每个组的命令。禁用时，则执行条件最大的组命令
enable_continuous_execution: true

# 是否启用离线执行
# 启用时，即使玩家离线，满足奖励组条件时仍然执行命令。禁用时，玩家在线才执行命令。
# 当你的命令必须要求玩家在线时，建议禁用
enable_offline_execution: false

# 累计Points奖励组
groups:
  # 奖励组名称,请按顺序使用正整数来命名，例如 1-10等
  1:
    # 该奖励组名称
    name: "累充100礼包"
    # 触发条件
    total: 100
    commands:
      - "这里填写达成条件后要执行的控制台命令"
      - "例如eco give %player_name% 200"
    prompt: "这里填写指令执行完成后的提示"
  2:
    name: "XXX"
    total: 200
    commands:
      - "XXX"
    prompt: "XXX"

# Points变化记录
logger:
  # 是否启用Points变化记录
  enable: false
  # 记录方式，填"mysql" 或者 “local”
  type: local
  # 记录在mysql的表名称（记录方式为"mysql"时生效）
  logger_table: PointsChange

# 数据库配置
mysql:
  # 是否启用数据库
  enable: false
  host: localhost
  port: 3306
  user: root
  password: ""
  database: database
  #  保存数据的表，不存在则创建表
  table: TotalPoints
  # 连接参数
  params: "?useSSL=false"

