# Points别名
name: '点券'

# 启用插件
enable: true

# 是否启用 PlaceholderAPI 变量
enable_papi: true

# 启用连续执行
# 启用时，当一次性满足多个奖励组的条件时，依次执行每个组的命令。禁用时，则执行条件最大的组命令
enable_ontinuous_execution: true

# 累计Points奖励组
groups:
  # 组名,请按顺序使用正整数来命名
  1:
    name: "累充100礼包"
    total: 100
    commands:
      - "填写达成条件后要执行的控制台命令"
      - "例如eco give %player_name% 200"
    prompt: "填写指令执行完成后的提示"
  2:
    name: "XXX"
    total: 200
    commands:
      - "XXX"
    prompt: "XXX"

# 数据库配置
mysql:
  # 是否启用数据库
  enable: false
  host: localhost
  port: 3306
  user: root
  password: ""
  database: database
  #  保存数据的表，不存在则创建表
  table: TotalPoints
  # 连接参数
  params: "?useSSL=false"

