name: TotalPoints
version: '${project.version}'
main: me.z5882852.totalpoints.TotalPoints
depend: [PlayerPoints]
softdepend: [PlaceholderAPI]
authors: [ z5882852 ]
description: 基于PlayerPoints的累计Points插件
commands:
  totalpoints:
    aliases: tpw
    usage: "/tpw <param>"

permissions:
  totalpoints.default:
    description: "所有玩家权限"
    default: true
    children:
      totalpoints.default.help: true
      totalpoints.default.look: true
      totalpoints.default.lookgroup: true
      totalpoints.default.get: true
  totalpoints.admin:
    description: "所有管理员权限"
    default: op
    children:
      totalpoints.admin.add: true
      totalpoints.admin.remove: true
      totalpoints.admin.set: true
      totalpoints.admin.reload: true
      totalpoints.admin.setgroup: true
      totalpoints.admin.give: true
